### ISSUE TITLE
Fail to unpickle

### ISSUE THREAD

**Issue by yjlolo** [mobeets/classifying-vae-lstm#1]
I fail to unpickle the dataset `JSB Chorales_Cs.pickle` with the suggested [line](https://github.com/mobeets/classifying-vae-lstm/blob/042a898558a967a37d1246a51b4c978d08783b7b/code/utils/pianoroll.py#L80)

Firstly, the [post](https://stackoverflow.com/questions/49579282/cant-find-module-cpickle-using-python-3-5-and-anaconda) suggests to change `import cPickle` to `import pickle` in Python 3.5

    import pickle
    D = pickle.load(open('JSB Chorales_Cs.pickle'))

it gives error `TypeError: a bytes-like object is required, not 'str'`. Then I follow the [post](https://stackoverflow.com/questions/39146039/pickle-typeerror-a-bytes-like-object-is-required-not-str) and change to

    D = pickle.load(open('JSB Chorales_Cs.pickle', mode='rb'))

but it gives error `EOFError: Ran out of input`

I wonder if it is the compatibility issue between Python 2 and 3; may I know if it is possible that you have the dataset runnable for Python 3? Please clarify if I missed something.

Thanks!

**Comment by mobeets** [comment]
Interesting, I don't have any trouble loading it in python 3.6.5 with `d = pickle.load(open('JSB Chorales_Cs.pickle', mode='rb'))`.

Are you sure the pickle file was fully downloaded? That's apparently a common error to get when the file exists but is empty. The file should be 2079064 bytes, just for comparison.

**Comment by yjlolo** [comment]
Sorry, it was my bad. Another attempt of download enabled unpickling; perhaps I mis-downloaded the files several time until the last one.
